export const DEMO_SOURCE = Object.freeze({
  mode: "synthetic",
  seed: "cw-eu-2026-09",
  label: "Synthetic demo data",
});

// City-center points for the illustrative map only; they are not charger coordinates.
export const ownSites = Object.freeze([
  {
    id: "NL-RTM-01",
    name: "Maasboulevard",
    city: "Rotterdam",
    coordinates: { lat: 51.9244, lon: 4.4777 },
    country: "NL",
    setting: "Public charging hub",
    parkingSpaces: 108,
    chargePoints: 32,
    online: 31,
    liveSessions: 2,
    utilisation: 62,
    capacityKw: 600,
    currentKw: 281,
    tariff: 0.59,
  },
  {
    id: "NL-AMS-02",
    name: "Arena parking P2",
    city: "Amsterdam",
    coordinates: { lat: 52.3676, lon: 4.9041 },
    country: "NL",
    setting: "Event parking",
    parkingSpaces: 480,
    chargePoints: 44,
    online: 43,
    liveSessions: 2,
    utilisation: 75,
    capacityKw: 900,
    currentKw: 560,
    tariff: 0.55,
  },
  {
    id: "NL-UTR-03",
    name: "Jaarbeurs P4",
    city: "Utrecht",
    coordinates: { lat: 52.0907, lon: 5.1214 },
    country: "NL",
    setting: "Parking garage",
    parkingSpaces: 310,
    chargePoints: 30,
    online: 30,
    liveSessions: 1,
    utilisation: 51,
    capacityKw: 540,
    currentKw: 222,
    tariff: 0.52,
  },
  {
    id: "NL-EIN-04",
    name: "High Tech Campus",
    city: "Eindhoven",
    coordinates: { lat: 51.4416, lon: 5.4697 },
    country: "NL",
    setting: "Workplace campus",
    parkingSpaces: 146,
    chargePoints: 20,
    online: 19,
    liveSessions: 1,
    utilisation: 46,
    capacityKw: 360,
    currentKw: 148,
    tariff: 0.48,
  },
  {
    id: "BE-ANR-01",
    name: "Antwerpen Zuid P+R",
    city: "Antwerpen",
    coordinates: { lat: 51.2194, lon: 4.4025 },
    country: "BE",
    setting: "Park and ride",
    parkingSpaces: 260,
    chargePoints: 28,
    online: 28,
    liveSessions: 1,
    utilisation: 58,
    capacityKw: 500,
    currentKw: 238,
    tariff: 0.61,
  },
  {
    id: "BE-GEN-02",
    name: "Gent Zuid Parking",
    city: "Gent",
    coordinates: { lat: 51.0543, lon: 3.7174 },
    country: "BE",
    setting: "City parking",
    parkingSpaces: 195,
    chargePoints: 24,
    online: 23,
    liveSessions: 1,
    utilisation: 43,
    capacityKw: 420,
    currentKw: 166,
    tariff: 0.57,
  },
  {
    id: "BE-BRU-03",
    name: "Brussels North P2",
    city: "Brussel",
    coordinates: { lat: 50.8503, lon: 4.3517 },
    country: "BE",
    setting: "Parking garage",
    parkingSpaces: 340,
    chargePoints: 36,
    online: 35,
    liveSessions: 1,
    utilisation: 68,
    capacityKw: 700,
    currentKw: 432,
    tariff: 0.62,
  },
  {
    id: "BE-LEU-04",
    name: "Leuven Campus West",
    city: "Leuven",
    coordinates: { lat: 50.8798, lon: 4.7005 },
    country: "BE",
    setting: "Workplace campus",
    parkingSpaces: 85,
    chargePoints: 16,
    online: 16,
    liveSessions: 1,
    utilisation: 39,
    capacityKw: 300,
    currentKw: 108,
    tariff: 0.54,
  },
]);

export const liveSessions = Object.freeze([
  {
    id: "CW-RTM-1042",
    siteId: "NL-RTM-01",
    chargePoint: "RTM-02",
    connector: "CCS",
    access: "ChargeWeave app",
    vehicle: "Kia EV6",
    startedAt: "2026-09-26T10:31:00+02:00",
    durationMin: 27,
    energyKwh: 24.8,
    amount: 12.40,
    status: "Charging",
  },
  {
    id: "CW-AMS-3108",
    siteId: "NL-AMS-02",
    chargePoint: "AMS-06",
    connector: "CCS",
    access: "Chargecard",
    vehicle: "Volvo EX30",
    startedAt: "2026-09-26T10:17:00+02:00",
    durationMin: 41,
    energyKwh: 31.2,
    amount: 17.14,
    status: "Charging",
  },
  {
    id: "CW-UTR-0837",
    siteId: "NL-UTR-03",
    chargePoint: "UTR-04",
    connector: "Type 2",
    access: "Fleet agreement",
    vehicle: "Renault Megane E-Tech",
    startedAt: "2026-09-26T10:40:00+02:00",
    durationMin: 18,
    energyKwh: 15.6,
    amount: 8.42,
    status: "Charging",
  },
  {
    id: "CW-EIN-0194",
    siteId: "NL-EIN-04",
    chargePoint: "EIN-01",
    connector: "CCS",
    access: "ChargeWeave app",
    vehicle: "Volkswagen ID.4",
    startedAt: "2026-09-26T10:06:00+02:00",
    durationMin: 52,
    energyKwh: 42.3,
    amount: 20.30,
    status: "Charging",
  },
  {
    id: "CW-ANR-2201",
    siteId: "BE-ANR-01",
    chargePoint: "ANR-05",
    connector: "CCS",
    access: "Chargecard",
    vehicle: "BMW i4",
    startedAt: "2026-09-26T10:24:00+02:00",
    durationMin: 34,
    energyKwh: 28.1,
    amount: 16.86,
    status: "Charging",
  },
  {
    id: "CW-GEN-0612",
    siteId: "BE-GEN-02",
    chargePoint: "GEN-11",
    connector: "Type 2",
    access: "ChargeWeave app",
    vehicle: "Polestar 2",
    startedAt: "2026-09-26T10:37:00+02:00",
    durationMin: 21,
    energyKwh: 17.9,
    amount: 10.56,
    status: "Charging",
  },
  {
    id: "CW-BRU-3305",
    siteId: "BE-BRU-03",
    chargePoint: "BRU-03",
    connector: "CCS",
    access: "Chargecard",
    vehicle: "Mercedes EQE",
    startedAt: "2026-09-26T10:12:00+02:00",
    durationMin: 46,
    energyKwh: 36.5,
    amount: 21.90,
    status: "Charging",
  },
  {
    id: "CW-LEU-0718",
    siteId: "BE-LEU-04",
    chargePoint: "LEU-02",
    connector: "Type 2",
    access: "Fleet agreement",
    vehicle: "Hyundai IONIQ 5",
    startedAt: "2026-09-26T10:27:00+02:00",
    durationMin: 29,
    energyKwh: 21.8,
    amount: 12.00,
    status: "Charging",
  },
  {
    id: "CW-AMS-3114",
    siteId: "NL-AMS-02",
    chargePoint: "AMS-16",
    connector: "CCS",
    access: "Chargecard",
    vehicle: "Tesla Model 3",
    startedAt: "2026-09-26T10:45:00+02:00",
    durationMin: 13,
    energyKwh: 11.1,
    amount: 7.00,
    status: "Charging",
  },
  {
    id: "CW-RTM-1019",
    siteId: "NL-RTM-01",
    chargePoint: "RTM-12",
    connector: "CCS",
    access: "ChargeWeave app",
    vehicle: "Audi Q4 e-tron",
    startedAt: "2026-09-26T10:43:00+02:00",
    durationMin: 15,
    energyKwh: 12.4,
    amount: 6.80,
    status: "Charging",
  },
]);

// City-center points for synthetic roaming fixtures; they are not charger coordinates.
export const roamingSessions = Object.freeze([
  {
    id: "RC-2026-091842",
    country: "Germany",
    countryCode: "DE",
    partner: "RheinCharge",
    location: "Aachen Hauptbahnhof",
    coordinates: { lat: 50.7753, lon: 6.0839 },
    chargePoint: "DE-AC-044",
    token: "•••• 4821",
    energyKwh: 38.4,
    amount: 24.96,
    cdrStatus: "Accepted",
    settlement: "Ready",
    recordedAt: "2026-09-26T09:52:00+02:00",
  },
  {
    id: "RC-2026-091831",
    country: "France",
    countryCode: "FR",
    partner: "NordLink",
    location: "Lille Centre",
    coordinates: { lat: 50.6292, lon: 3.0573 },
    chargePoint: "FR-LIL-128",
    token: "•••• 4821",
    energyKwh: 22.7,
    amount: 16.36,
    cdrStatus: "Accepted",
    settlement: "Ready",
    recordedAt: "2026-09-26T09:18:00+02:00",
  },
  {
    id: "RC-2026-091790",
    country: "Belgium",
    countryCode: "BE",
    partner: "Local network partner",
    location: "Liège Guillemins",
    coordinates: { lat: 50.6326, lon: 5.5797 },
    chargePoint: "BE-LGG-016",
    token: "•••• 1066",
    energyKwh: 31.6,
    amount: 20.54,
    cdrStatus: "Correction received",
    settlement: "Review required",
    recordedAt: "2026-09-26T08:46:00+02:00",
  },
  {
    id: "RC-2026-091751",
    country: "Netherlands",
    countryCode: "NL",
    partner: "City network partner",
    location: "Maastricht Vrijthof",
    coordinates: { lat: 50.8514, lon: 5.6900 },
    chargePoint: "NL-MST-061",
    token: "•••• 4821",
    energyKwh: 17.2,
    amount: 11.01,
    cdrStatus: "Accepted",
    settlement: "Ready",
    recordedAt: "2026-09-26T08:09:00+02:00",
  },
  {
    id: "RC-2026-091702",
    country: "Denmark",
    countryCode: "DK",
    partner: "NorthGrid",
    location: "Copenhagen Metro",
    coordinates: { lat: 55.6761, lon: 12.5683 },
    chargePoint: "DK-CPH-207",
    token: "•••• 7714",
    energyKwh: 42.1,
    amount: 30.31,
    cdrStatus: "Awaiting partner response",
    settlement: "On hold",
    recordedAt: "2026-09-26T07:37:00+02:00",
  },
  {
    id: "RC-2026-091641",
    country: "Austria",
    countryCode: "AT",
    partner: "Alpine Charge",
    location: "Wien Westbahnhof",
    coordinates: { lat: 48.2082, lon: 16.3738 },
    chargePoint: "AT-W-099",
    token: "•••• 1066",
    energyKwh: 29.5,
    amount: 22.13,
    cdrStatus: "Accepted",
    settlement: "Ready",
    recordedAt: "2026-09-26T06:55:00+02:00",
  },
]);

export const recentActivity = Object.freeze([
  {
    tone: "good",
    title: "Charge point available",
    detail: "Maasboulevard · Rotterdam",
    time: "2 min ago",
  },
  {
    tone: "info",
    title: "Chargecard session started",
    detail: "Antwerpen Zuid P+R · Antwerpen",
    time: "8 min ago",
  },
  {
    tone: "warn",
    title: "Roaming correction needs review",
    detail: "Liège Guillemins · CDR correction",
    time: "14 min ago",
  },
  {
    tone: "good",
    title: "Settlement batch reconciled",
    detail: "Partner network · 42 records",
    time: "31 min ago",
  },
]);

export const dataEntities = Object.freeze([
  { name: "ChargingSite", type: "Asset", fields: 18, selected: true },
  { name: "ChargePoint", type: "Asset", fields: 24 },
  { name: "Session", type: "Operation", fields: 31 },
  { name: "ChargecardToken", type: "Identity", fields: 12 },
  { name: "ChargingDetailRecord", type: "Commercial", fields: 26 },
  { name: "RoamingSettlement", type: "Commercial", fields: 22 },
  { name: "MeterReading", type: "Evidence", fields: 17 },
  { name: "TariffVersion", type: "Commercial", fields: 16 },
]);

export const financialLines = Object.freeze([
  { category: "Charging revenue", basis: "Sessions on owned network", amount: 24630.40, scope: "NL + BE", treatment: "Revenue" },
  { category: "Energy procurement", basis: "Delivered energy allocation", amount: -8120.20, scope: "NL + BE", treatment: "Cost" },
  { category: "Roaming partner settlement", basis: "Chargecard partner CDRs", amount: -7892.40, scope: "EU partner markets", treatment: "Payable" },
  { category: "Payment and variable operations", basis: "Payment and transaction costs", amount: -2380.00, scope: "NL + BE", treatment: "Cost" },
]);

export function getSiteMetrics(sites = ownSites) {
  return sites.reduce(
    (total, site) => ({
      sites: total.sites + 1,
      chargePoints: total.chargePoints + site.chargePoints,
      online: total.online + site.online,
      parkingSpaces: total.parkingSpaces + site.parkingSpaces,
      liveSessions: total.liveSessions + site.liveSessions,
      capacityKw: total.capacityKw + site.capacityKw,
      currentKw: total.currentKw + site.currentKw,
    }),
    {
      sites: 0,
      chargePoints: 0,
      online: 0,
      parkingSpaces: 0,
      liveSessions: 0,
      capacityKw: 0,
      currentKw: 0,
    },
  );
}

export function filterByCountry(rows, country = "all") {
  return country === "all" ? [...rows] : rows.filter((row) => row.country === country);
}

export function filterByQuery(rows, query, fields) {
  const normalized = String(query ?? "").trim().toLocaleLowerCase();
  if (!normalized) return [...rows];
  return rows.filter((row) =>
    fields.some((field) => String(row[field] ?? "").toLocaleLowerCase().includes(normalized)),
  );
}

export function formatEuro(value) {
  return new Intl.NumberFormat("nl-NL", {
    style: "currency",
    currency: "EUR",
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(value);
}

export function formatNumber(value) {
  return new Intl.NumberFormat("nl-NL", { maximumFractionDigits: 1 }).format(value);
}

export function findSite(siteId) {
  return ownSites.find((site) => site.id === siteId);
}
