PREFIX cd: <https://example.org/charge-domain#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?this WHERE { ?this rdf:type/rdfs:subClassOf* cd:ServiceEntitlement . ?this cd:entitlementState cd:entitlementState_Active; cd:serviceAgreement ?a; cd:validFrom ?t. OPTIONAL {?this cd:validUntil ?until} FILTER NOT EXISTS {?a cd:agreementState cd:agreementState_Active; cd:validFrom ?s. OPTIONAL {?a cd:validUntil ?e} FILTER(?t>=?s && (!BOUND(?e) || (?t<?e && BOUND(?until) && ?until<=?e)))} }
