PREFIX cd: <https://example.org/charge-domain#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?this WHERE { ?this rdf:type/rdfs:subClassOf* cd:BenefitReservation . ?this cd:reservationState cd:reservationState_Consumed; cd:allowance ?a; cd:billingPeriod ?b; cd:session ?s; cd:reservedValue ?v. FILTER NOT EXISTS {?this cd:consumption ?c. ?c cd:allowance ?a; cd:billingPeriod ?b; cd:session ?s; cd:consumedValue ?used. FILTER(?used>=0 && ?used<=?v)} }
