PREFIX cd: <https://example.org/charge-domain#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?this WHERE { ?this rdf:type/rdfs:subClassOf* cd:AllowanceSponsorship . ?this cd:validFrom ?a; cd:validUntil ?b; cd:serviceAgreement ?agreement. ?agreement cd:validFrom ?start. OPTIONAL {?agreement cd:validUntil ?end} FILTER(?b<=?a || ?a<?start || (BOUND(?end) && ?b>?end)) }
