PREFIX cd: <https://example.org/charge-domain#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?this WHERE { ?this rdf:type/rdfs:subClassOf* cd:TemporalCommit . {?this cd:sourceWatermark ?w. FILTER NOT EXISTS {?w cd:watermarkState cd:watermarkState_Complete}} UNION {?this cd:recordedAt ?r; cd:sourceWatermark/cd:watermarkAt ?w. FILTER(?w>?r)} UNION {?this cd:sourceWatermark ?x,?y. ?x cd:sourceSystem ?source; cd:sourcePartition ?part. ?y cd:sourceSystem ?source; cd:sourcePartition ?part. FILTER(?x!=?y)} UNION {?this cd:previousCommit/cd:sourceWatermark ?old. ?old cd:sourceSystem ?source; cd:sourcePartition ?part; cd:sourceOffset ?offset; cd:completeThrough ?time. FILTER NOT EXISTS {?this cd:sourceWatermark ?new. ?new cd:sourceSystem ?source; cd:sourcePartition ?part; cd:sourceOffset ?newOffset; cd:completeThrough ?newTime. FILTER(?newOffset>=?offset && ?newTime>=?time)}} }
