PREFIX cd: <https://example.org/charge-domain#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?this WHERE { ?this rdf:type/rdfs:subClassOf* cd:CommercialOffer . ?this cd:currency ?cur; cd:selectedTariff ?tariff; cd:priceDisplay ?display. FILTER(!EXISTS {?display cd:displayCurrency ?cur} || !EXISTS {?tariff cd:currency ?cur} || EXISTS {?display cd:selectedTariff ?other. FILTER(?other!=?tariff)}) }
