PREFIX cd: <https://example.org/charge-domain#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?this WHERE { ?this rdf:type/rdfs:subClassOf* cd:Refund . ?this cd:refundAmount ?amount; cd:refundState ?state; cd:paymentCapture ?capture. FILTER(?amount<=0 || (?state=cd:refundState_Confirmed && !EXISTS {?capture cd:captureState cd:captureState_Confirmed})) }
