from pathlib import Path
import json
from rdflib import Graph,Namespace,Literal,BNode,RDF
P=Path(__file__).resolve().parents[1];C=Namespace('https://example.org/charge-domain#');SH=Namespace('http://www.w3.org/ns/shacl#')
PREFIX='PREFIX cd: <https://example.org/charge-domain#>\nPREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\nPREFIX owl: <http://www.w3.org/2002/07/owl#>\nPREFIX xsd: <http://www.w3.org/2001/XMLSchema#>\n'
rules=[]
def rule(key,target,message,body):rules.append(dict(id=key,target=target,message=message,query=PREFIX+'SELECT $this WHERE { '+body+' }'))
rule('B001','Record','Tenant-owned object references must remain within the same tenant.','$this cd:tenant ?t; ?p ?other. ?p cd:sameTenant true. ?other cd:tenant ?u. FILTER(?t != ?u)')
rule('B002','Record','Canonical IDs are unique across all records within a tenant.','$this cd:tenant ?t; cd:canonicalId ?id. ?other cd:tenant ?t; cd:canonicalId ?id. FILTER(?other != $this)')
rule('B003','Record','Record cannot instantiate explicitly disjoint domain classes.','$this a ?a, ?b. ?set owl:members ?members; a owl:AllDisjointClasses. ?members rdf:rest*/rdf:first ?a, ?b. FILTER(?a != ?b)')
rule('B004','Record','Unknown predicates in the controlled namespace are rejected.','$this ?p ?v. FILTER(STRSTARTS(STR(?p),"https://example.org/charge-domain#")) FILTER NOT EXISTS {?p a owl:ObjectProperty} FILTER NOT EXISTS {?p a owl:DatatypeProperty}')
rule('B005','CustomFieldValue','Extension value datatype must match its declared definition.','$this cd:valueDatatype ?a; cd:fieldDefinition/cd:fieldDatatype ?b. FILTER(?a != ?b)')
rule('B006','OperatorService','Operator service hierarchy must be acyclic.','$this cd:parentService+ $this.')
rule('B007','ChargingStation','Gateway station chains must be acyclic.','$this cd:gatewayStation+ $this.')
rule('B008','ChargingStation','Direct communication requires a protocol endpoint.','$this cd:communicationMode cd:communicationMode_Direct. FILTER NOT EXISTS {$this cd:protocolEndpoint ?e}')
rule('B009','ChargingStation','Gateway communication requires a gateway station.','$this cd:communicationMode cd:communicationMode_Gateway. FILTER NOT EXISTS {$this cd:gatewayStation ?e}')
rule('B010','ChargingStation','Commercial stations require a physical site.','$this cd:stationUse ?s. FILTER(?s IN (cd:stationUse_Public,cd:stationUse_Private)) FILTER NOT EXISTS {$this cd:site ?e}')
rule('B011','ChargingStation','Personal stations require an owner account.','$this cd:stationUse cd:stationUse_Personal. FILTER NOT EXISTS {$this cd:ownerAccount ?o}')
rule('B012','ChargingStation','Charging area and station site must agree.','$this cd:site ?a; cd:area/cd:site ?b. FILTER(?a != ?b)')
rule('B013','ParkingSpace','Parking area and bay site must agree.','$this cd:site ?a; cd:area/cd:site ?b. FILTER(?a != ?b)')
rule('B014','PaymentTerminal','A payment terminal must serve exactly one station or area.','{FILTER NOT EXISTS {$this cd:station ?s} FILTER NOT EXISTS {$this cd:area ?a}} UNION {$this cd:station ?s; cd:area ?a}')
rule('B015','ElectricalCircuit','Physical circuit hierarchy must be acyclic.','$this cd:parentCircuit+ $this.')
rule('B016','LoadControlGroup','Virtual control hierarchy must be acyclic.','$this cd:parentControlGroup+ $this.')
rule('B017','ElectricalCircuit','Nested physical circuits must remain on the same site.','$this cd:site ?a; cd:parentCircuit/cd:site ?b. FILTER(?a != ?b)')
rule('B018','LoadControlGroup','Nested control groups must remain on the same site.','$this cd:site ?a; cd:parentControlGroup/cd:site ?b. FILTER(?a != ?b)')
rule('B019','ChargingUnit','Minimum current cannot exceed maximum current.','$this cd:minimumCurrentA ?a; cd:maximumCurrentA ?b. FILTER(?a > ?b)')
rule('B020','PublicListing','Unknown payment availability cannot assert payment-option values.','$this cd:paymentOptionsKnowledge cd:paymentOptionsKnowledge_Unknown; cd:paymentOptionCode ?o.')
rule('B021','AuthorizationRequest','Non-free authorization requires a credential or customer reference.','$this cd:authorizationMethod ?m. FILTER(?m != cd:authorizationMethod_LocalFree) FILTER NOT EXISTS {$this cd:credential ?c} FILTER NOT EXISTS {$this cd:customer ?u}')
rule('B022','AuthorizationDecision','Authorization decision cannot predate its request.','$this cd:decidedAt ?d; cd:authorizationRequest/cd:requestedAt ?r. FILTER(?d < ?r)')
rule('B023','ChargingSession','Completed sessions require end time and end evidence.','$this cd:sessionState cd:sessionState_Completed. FILTER(!EXISTS {$this cd:endedAt ?e} || !EXISTS {$this cd:endEvidence ?f})')
rule('B024','ChargingSession','Session end cannot precede session start.','$this cd:startedAt ?a; cd:endedAt ?b. FILTER(?b < ?a)')
rule('B025','ChargingSession','Finalization evidence must describe the same session.','$this cd:endEvidence/cd:session ?s. FILTER(?s != $this)')
rule('B026','ChargingSession','Active charging requires accepted authorization.','$this cd:sessionState ?s; cd:authorizationDecision/cd:decision ?d. FILTER(?s IN (cd:sessionState_Active,cd:sessionState_Suspended,cd:sessionState_Completed) && ?d != cd:decision_Accepted)')
rule('B027','ChargingSession','Selected tariff must be effective at session start.','$this cd:startedAt ?s; cd:selectedTariff ?t. ?t cd:validFrom ?a. OPTIONAL {?t cd:validUntil ?b} FILTER(?s < ?a || (BOUND(?b) && ?s >= ?b))')
rule('B028','ChargingSession','Authorization target must match the charged unit.','$this cd:chargingUnit ?a; cd:authorizationDecision/cd:authorizationRequest/cd:chargingUnit ?b. FILTER(?a != ?b)')
rule('B029','SourceEvent','A source timestamp ahead of receipt time requires a documented clock assessment.','$this cd:occurredAt ?a; cd:receivedAt ?b. FILTER(?b < ?a) FILTER NOT EXISTS {$this cd:clockAssessment ?c}')
rule('B030','SignedMeterEvidence','A verified signature must have a verification timestamp.','$this cd:signatureVerification cd:signatureVerification_Valid. FILTER NOT EXISTS {$this cd:verifiedAt ?d}')
rule('B031','ChargeDetailRecord','Local CDRs require a completed canonical session.','$this cd:recordOrigin cd:recordOrigin_Local. FILTER NOT EXISTS {$this cd:session/cd:sessionState cd:sessionState_Completed}')
rule('B032','ChargeDetailRecord','Original local CDR import and export energy must agree with the canonical session.','$this cd:recordOrigin cd:recordOrigin_Local; cd:session ?s; cd:importedEnergyKWh ?a; cd:exportedEnergyKWh ?b. FILTER NOT EXISTS {$this cd:correctionOf ?old} ?s cd:importedEnergyKWh ?c; cd:exportedEnergyKWh ?d. FILTER(?a != ?c || ?b != ?d)')
rule('B033','ChargeDetailRecord','CDR correction lineage must be acyclic.','$this cd:correctionOf+ $this.')
rule('B034','TariffVersion','Priced tariffs require at least one price component.','$this cd:tariffMode cd:tariffMode_Priced. FILTER NOT EXISTS {$this cd:priceComponent ?p}')
rule('B035','TariffVersion','Discount tariffs require an explicit base or a declared deferred base-selection policy.','$this cd:tariffMode cd:tariffMode_DiscountBased. FILTER NOT EXISTS {$this cd:baseTariffVersion ?b} FILTER NOT EXISTS {$this cd:baseTariffSelection ?mode. FILTER(?mode IN (cd:baseTariffSelection_SetBase,cd:baseTariffSelection_RoamingWholesale))}')
rule('B036','TariffVersion','Dynamic tariffs require a formula.','$this cd:tariffMode cd:tariffMode_Dynamic. FILTER NOT EXISTS {$this cd:dynamicPriceFormula ?f}')
rule('B037','TariffVersion','Tariff derivation must be acyclic.','$this cd:baseTariffVersion+ $this.')
rule('B038','TariffSet','Tariff assignment priorities within a set must be unique.','$this cd:tariffAssignment ?a,?b. ?a cd:priority ?p. ?b cd:priority ?p. FILTER(?a != ?b)')
rule('B039','ElectricityPriceInterval','Price intervals require exactly one explicit or recurring window.','{FILTER NOT EXISTS {$this cd:interval ?a} FILTER NOT EXISTS {$this cd:recurringWindow ?b}} UNION {$this cd:interval ?a; cd:recurringWindow ?b}')
rule('B040','EnergyMix','Generation fractions must sum to one within decimal tolerance.','{SELECT $this (SUM(?x) AS ?sum) WHERE {$this cd:sourceShare/cd:shareFraction ?x} GROUP BY $this} FILTER(ABS(?sum - 1) > 0.000001)')
rule('B041','DynamicPriceFormula','Dynamic price lower bound cannot exceed upper bound.','$this cd:minimumUnitPrice ?a; cd:maximumUnitPrice ?b. FILTER(?a > ?b)')
rule('B042','Record','Stored gross amount must equal rounded net plus rounded tax.','$this cd:netAmount ?n; cd:taxAmount ?t; cd:grossAmount ?g. FILTER(?g != ?n + ?t)')
rule('B043','Invoice','Invoice totals must agree with the sum of its lines.','$this cd:netAmount ?net; cd:taxAmount ?tax; cd:grossAmount ?gross. {SELECT $this (SUM(?n) AS ?ns) (SUM(?t) AS ?ts) (SUM(?g) AS ?gs) WHERE {$this cd:invoiceLine ?l. ?l cd:netAmount ?n; cd:taxAmount ?t; cd:grossAmount ?g} GROUP BY $this} FILTER(?net != ?ns || ?tax != ?ts || ?gross != ?gs)')
rule('B044','Invoice','Invoice line currencies must match the document.','$this cd:currency ?a; cd:invoiceLine/cd:currency ?b. FILTER(?a != ?b)')
rule('B045','PaymentAuthorization','Authorization currency must match its payment intent.','$this cd:currency ?a; cd:paymentIntent/cd:currency ?b. FILTER(?a != ?b)')
rule('B046','PaymentCapture','Capture currency must match its payment intent.','$this cd:currency ?a; cd:paymentIntent/cd:currency ?b. FILTER(?a != ?b)')
rule('B047','Refund','Refund currency must match the original capture.','$this cd:currency ?a; cd:paymentCapture/cd:currency ?b. FILTER(?a != ?b)')
rule('B048','PaymentCapture','Confirmed refunds may not exceed the confirmed capture amount.','$this cd:capturedAmount ?cap. {SELECT $this (SUM(?amount) AS ?total) WHERE {?r cd:paymentCapture $this; a cd:Refund; cd:refundState cd:refundState_Confirmed; cd:refundAmount ?amount} GROUP BY $this} FILTER(?total > ?cap)')
rule('B049','PaymentIntent','Confirmed captures may not exceed requested payment amount.','$this cd:requestedAmount ?limit. {SELECT $this (SUM(?amount) AS ?total) WHERE {?c cd:paymentIntent $this; a cd:PaymentCapture; cd:captureState cd:captureState_Confirmed; cd:capturedAmount ?amount} GROUP BY $this} FILTER(?total > ?limit)')
rule('B050','Journal','Posted journal must balance independently per currency.','$this cd:journalState cd:journalState_Posted. {SELECT $this ?currency (SUM(?amount) AS ?total) WHERE {$this cd:journalLine ?l. ?l cd:signedAmount ?amount; cd:currency ?currency} GROUP BY $this ?currency} FILTER(?total != 0)')
rule('B051','JournalLine','Journal line currency must match its ledger account.','$this cd:currency ?a; cd:ledgerAccount/cd:currency ?b. FILTER(?a != ?b)')
rule('B052','CorporateCostAllocation','Sponsor plus driver allocation must equal the total charge.','$this cd:totalAmount ?a; cd:sponsorAmount ?s; cd:driverAmount ?d. FILTER(?a != ?s + ?d)')
rule('B053','ReimbursementPolicy','Policy-sourced reimbursement requires an explicit electricity schedule.','$this cd:reimbursementRateSource cd:reimbursementRateSource_Policy. FILTER NOT EXISTS {$this cd:electricitySchedule ?s}')
rule('B054','ReimbursementPolicy','Station-sourced reimbursement must not embed a competing policy schedule.','$this cd:reimbursementRateSource cd:reimbursementRateSource_Station; cd:electricitySchedule ?s.')
rule('B055','ReimbursementPolicy','A contract-scoped reimbursement policy must identify its partner.','$this cd:serviceAgreement ?a. FILTER NOT EXISTS {$this cd:partner ?p}')
rule('B056','ReimbursementRecord','Reimbursement evidence must be for a personal station.','$this cd:session/cd:chargingUnit/cd:station/cd:stationUse ?k. FILTER(?k != cd:stationUse_Personal)')
rule('B057','ReimbursementRecord','Station-derived reimbursement requires the station electricity schedule.','$this cd:reimbursementPolicy/cd:reimbursementRateSource cd:reimbursementRateSource_Station. FILTER NOT EXISTS {$this cd:session/cd:chargingUnit/cd:station/cd:electricitySchedule ?s}')
rule('B058','EnergyCouponTemplate','Relative coupon validity requires a duration; fixed validity requires both dates.','{$this cd:validityMode cd:validityMode_DaysAfterRedemption. FILTER NOT EXISTS {$this cd:validityDays ?d}} UNION {$this cd:validityMode cd:validityMode_FixedWindow. FILTER(!EXISTS {$this cd:validFrom ?a} || !EXISTS {$this cd:validUntil ?b})}')
rule('B059','EnergyCoupon','Coupon consumption must not exceed its energy allowance; reversal records subtract.','$this cd:energyAllowanceKWh ?limit. {SELECT $this (SUM(?signed) AS ?total) WHERE {?c cd:energyCoupon $this; a cd:CouponConsumption; cd:consumedEnergyKWh ?e. BIND(IF(EXISTS {?c cd:reversalOf ?r},-?e,?e) AS ?signed)} GROUP BY $this} FILTER(?total > ?limit || ?total < 0)')
rule('B060','CouponConsumption','Coupon use must occur within its validity interval.','$this cd:consumedAt ?t; cd:energyCoupon ?c. ?c cd:validFrom ?a; cd:validUntil ?b. FILTER(?t < ?a || ?t >= ?b)')
rule('B061','CouponConsumption','Reversal must reference a consumption of the same coupon.','$this cd:energyCoupon ?a; cd:reversalOf/cd:energyCoupon ?b. FILTER(?a != ?b)')
rule('B062','ChargingSchedule','Schedule periods must lie within schedule validity.','$this cd:validFrom ?a; cd:validUntil ?b; cd:schedulePeriod ?p. ?p cd:periodStart ?s; cd:periodEnd ?e. FILTER(?s < ?a || ?e > ?b)')
rule('B063','ChargingSchedule','Schedule periods in one schedule must not overlap.','$this cd:schedulePeriod ?a,?b. ?a cd:periodStart ?s1; cd:periodEnd ?e1. ?b cd:periodStart ?s2; cd:periodEnd ?e2. FILTER(?a != ?b && ?s1 < ?e2 && ?s2 < ?e1)')
rule('B064','ForecastPoint','Forecast bounds must contain the predicted value.','$this cd:predictedValue ?v. OPTIONAL {$this cd:lowerBound ?a} OPTIONAL {$this cd:upperBound ?b} FILTER((BOUND(?a) && ?v < ?a) || (BOUND(?b) && ?v > ?b))')
rule('B065','AvailabilityResult','Availability seconds must be positive and bounded.','$this cd:eligibleSeconds ?a; cd:unavailableSeconds ?b. FILTER(?a <= 0 || ?b > ?a)')
rule('B066','AvailabilityResult','Availability fraction must agree with eligible and unavailable seconds.','$this cd:eligibleSeconds ?a; cd:unavailableSeconds ?b; cd:availabilityFraction ?f. FILTER(?a > 0 && ABS(?f-(1-?b/?a)) > 0.000001)')
rule('B067','WorkOrder','Completed work orders require timestamp and completion evidence.','$this cd:workState cd:workState_Completed. FILTER(!EXISTS {$this cd:completedAt ?t} || !EXISTS {$this cd:completionEvidence ?e})')
rule('B068','InstallationJob','Completed installations require commissioning evidence.','$this cd:jobState cd:jobState_Completed. FILTER(!EXISTS {$this cd:completedAt ?t} || !EXISTS {$this cd:commissioningEvidence ?e})')
rule('B069','FiscalizationAttempt','Accepted fiscalization requires an authority reference and fiscal evidence.','$this cd:fiscalizationState cd:fiscalizationState_Accepted. FILTER(!EXISTS {$this cd:authorityReference ?r} || !EXISTS {$this cd:fiscalDocument ?e})')
rule('B070','BrandProfile','The default language must be one of the supported languages.','$this cd:defaultLanguage ?l. FILTER NOT EXISTS {$this cd:supportedLanguage ?l}')
rule('B071','ActionApproval','Approved assistant actions must reference the exact proposed command.','$this cd:approvalDecision cd:approvalDecision_Approved; cd:recommendation ?r. FILTER NOT EXISTS {$this cd:approvedCommand ?c. ?r cd:proposedCommand ?c}')
rule('B072','EventDelivery','Delivered events must not retain a retry timestamp.','$this cd:deliveryState cd:deliveryState_Delivered; cd:nextRetryAt ?r.')
rule('B073','RemoteCommand','Successful command state requires successful completion evidence, not acknowledgement alone.','$this cd:commandState cd:commandState_Succeeded. FILTER NOT EXISTS {?o a cd:CommandOutcome; cd:command $this; cd:outcomeKind cd:outcomeKind_Completion; cd:outcomeState cd:outcomeState_Succeeded}')
rule('B074','StateTransition','Lifecycle transition must be permitted for the stated property and prior/next codes.','$this cd:stateProperty ?p; cd:previousState ?a; cd:nextState ?b. FILTER NOT EXISTS {?rule cd:transitionProperty ?p; cd:fromState ?a; cd:toState ?b}')
rule('B075','Record','Optional effective timestamps must define a positive half-open interval.','$this cd:validFrom ?a; cd:validUntil ?b. FILTER(?b <= ?a)')
rule('B076','TimeWindow','Half-open interval must have positive duration.','$this cd:startsAt ?a; cd:endsAt ?b. FILTER(?b <= ?a)')
rule('B077','SchedulePeriod','Schedule interval must have positive duration.','$this cd:periodStart ?a; cd:periodEnd ?b. FILTER(?b <= ?a)')
rule('B078','RemoteCommand','Command expiry must be after request time.','$this cd:requestedAt ?a; cd:expiresAt ?b. FILTER(?b <= ?a)')
rule('B079','ReimbursementPolicy','Inclusive reimbursement end date cannot precede the start date.','$this cd:validFromDate ?a; cd:validUntilDate ?b. FILTER(?b < ?a)')
rule('B080','Invoice','Due date cannot precede invoice issuance.','$this cd:issuedAt ?a; cd:dueAt ?b. FILTER(?b < ?a)')
rule('B081','Reservation','Reservation expiry must be after reservation time.','$this cd:reservedAt ?a; cd:expiresAt ?b. FILTER(?b <= ?a)')
rule('B082','RecurringWindow','Local time ordering must agree with the overnight flag.','$this cd:localStart ?a; cd:localEnd ?b; cd:spansMidnight ?s. FILTER((! ?s && ?b <= ?a) || (?s && ?b > ?a))')
rule('B083','PaymentAuthorization','Authorization expiry must be after authorization time.','$this cd:authorizedAt ?a; cd:expiresAt ?b. FILTER(?b <= ?a)')
rule('B084','ChargeDetailRecord','When a CDR has a tariff snapshot their currencies must agree.','$this cd:currency ?a; cd:selectedTariff/cd:currency ?b. FILTER(?a != ?b)')
rule('B085','SettlementBatch','Settlement items must have the batch currency and agreement.','$this cd:currency ?a; cd:serviceAgreement ?b; cd:settlementItem ?i. ?i cd:currency ?c; cd:serviceAgreement ?d. FILTER(?a != ?c || ?b != ?d)')
rule('B086','CorporateBillingSnapshot','Snapshot policy version must identify the referenced immutable policy version.','$this cd:policyVersion ?a; cd:corporateBillingPolicy/cd:policyVersion ?b. FILTER(?a != ?b)')
rule('B087','VoucherRedemption','Voucher and wallet currencies must agree.','$this cd:voucher/cd:currency ?a; cd:wallet/cd:currency ?b. FILTER(?a != ?b)')
rule('B088','FirmwareDeployment','Firmware must list the station model as compatible.','$this cd:firmware ?f; cd:station/cd:equipmentModel ?m. FILTER NOT EXISTS {?f cd:compatibleModel ?m}')
rule('B089','ChargingStation','Station using personal reimbursement must be classified personal.','$this cd:reimbursementPolicy ?p; cd:stationUse ?s. FILTER(?s != cd:stationUse_Personal)')
rule('B090','CorporateChargerRule','Corporate pricing limits cannot be negative.','$this ?p ?v. FILTER(?p IN (cd:costCapPerKWh,cd:maximumEnergyUnitPrice,cd:maximumIdleUnitPrice,cd:maximumFlatFee)) FILTER(?v < 0)')
rule('B091','DiscountRule','Percentage discounts are bounded between zero and one hundred.','$this cd:discountBasis cd:discountBasis_Percentage; cd:discountMagnitude ?v. FILTER(?v < 0 || ?v > 100)')
rule('B092','FeeBounds','Component fee floor cannot exceed its ceiling.','$this cd:minimumCharge ?a; cd:maximumCharge ?b. FILTER(?a > ?b)')
rule('B093','PriceTier','Tier upper bound must exceed its inclusive lower bound.','$this cd:tierLowerBound ?a; cd:tierUpperBound ?b. FILTER(?b <= ?a)')
rule('B094','SessionPricingPolicy','Session charge floor cannot exceed its ceiling.','$this cd:minimumSessionCharge ?a; cd:maximumSessionCharge ?b. FILTER(?a > ?b)')
rule('B095','Payout','Confirmed payouts require confirmation time.','$this cd:payoutState cd:payoutState_Confirmed. FILTER NOT EXISTS {$this cd:confirmedAt ?t}')
rule('B096','PayoutBatch','Payout batch currency and total must agree with included payouts.','{$this cd:currency ?a; cd:payout/cd:currency ?b. FILTER(?a != ?b)} UNION {$this cd:batchTotal ?t. {SELECT $this (SUM(?v) AS ?s) WHERE {$this cd:payout/cd:payoutAmount ?v} GROUP BY $this} FILTER(?t != ?s)}')
rule('B097','PowerCabinet','DC cabinet capacity must be positive and at least one module.','$this cd:totalCabinetPowerKW ?t; cd:moduleSizeKW ?m. FILTER(?m <= 0 || ?t < ?m)')
rule('B098','PowerModuleAllocation','Allocated power must agree with module count and not exceed cabinet capacity.','$this cd:allocatedModules ?n; cd:allocatedPowerKW ?p; cd:powerCabinet ?c. ?c cd:moduleSizeKW ?m; cd:totalCabinetPowerKW ?total. FILTER(?p != ?n * ?m || ?p > ?total)')
rule('B099','ChargingProfile','Recurring profiles require recurrence kind; transaction-specific profiles require a transaction.','{$this cd:profileKind cd:profileKind_Recurring. FILTER NOT EXISTS {$this cd:recurrenceKind ?r}} UNION {$this cd:profilePurpose cd:profilePurpose_TransactionSpecific. FILTER NOT EXISTS {$this cd:protocolTransaction ?t}}')
rule('B100','AccessTokenLease','Access-token expiration must follow issuance.','$this cd:issuedAt ?a; cd:expiresAt ?b. FILTER(?b <= ?a)')
rule('B101','AccessTokenLease','Revoked access tokens require a revocation timestamp.','$this cd:accessTokenState cd:accessTokenState_Revoked. FILTER NOT EXISTS {$this cd:revokedAt ?r}')
rule('B102','PriceComponent','Pricing component tiers must not overlap.','$this cd:priceTier ?a,?b. ?a cd:tierLowerBound ?al. ?b cd:tierLowerBound ?bl. OPTIONAL {?a cd:tierUpperBound ?au} OPTIONAL {?b cd:tierUpperBound ?bu} FILTER(?a != ?b && (!BOUND(?au) || ?bl < ?au) && (!BOUND(?bu) || ?al < ?bu))')
rule('B103','PreauthorizationPolicy','Hold amounts must be nonnegative.','$this ?p ?v. FILTER(?p IN (cd:initialHoldAmount,cd:incrementalHoldAmount)) FILTER(?v < 0)')
rule('B104','CorporateCostAllocation','Allocation snapshot must refer to the allocated session.','$this cd:session ?a; cd:corporateSnapshot/cd:session ?b. FILTER(?a != ?b)')
rule('B105','CouponConsumption','Coupon reversal must not reverse a reversal or exceed its original amount.','$this cd:reversalOf ?r; cd:consumedEnergyKWh ?v. ?r cd:consumedEnergyKWh ?old. FILTER(EXISTS {?r cd:reversalOf ?r2} || ?v > ?old)')
rule('B106','PaymentCapture','Confirmed captures require a provider confirmation reference.','$this cd:captureState cd:captureState_Confirmed. FILTER NOT EXISTS {$this cd:providerReference ?r}')
rule('B107','TariffVersion','A discount-based tariff requires explicit discount rules.','$this cd:tariffMode cd:tariffMode_DiscountBased. FILTER NOT EXISTS {$this cd:discountRule ?d}')
rule('B108','PowerModuleAllocation','Allocated charging unit must be served by the cabinet.','$this cd:chargingUnit ?u; cd:powerCabinet ?c. FILTER NOT EXISTS {?c cd:servedUnit ?u}')
rule('B109','RatingCalculation','Rating a deferred-base discount requires the resolved immutable base tariff.','$this cd:selectedTariff/cd:baseTariffSelection ?mode. FILTER(?mode IN (cd:baseTariffSelection_SetBase,cd:baseTariffSelection_RoamingWholesale)) FILTER NOT EXISTS {$this cd:tariffResolution/cd:resolvedBaseTariff ?base}')
for extra in json.loads((P/'model/audit-rules.json').read_text()):
 rule(extra['id'],extra['target'],extra['title'],extra['body'])
# Enumeration transitions are domain policy, not a copied vendor state machine.
transitions={
'sessionState':{'Pending':['Starting','Failed'],'Starting':['Active','Failed','ReconciliationRequired'],'Active':['Suspended','Ending','ReconciliationRequired'],'Suspended':['Active','Ending','ReconciliationRequired'],'Ending':['Completed','ReconciliationRequired'],'ReconciliationRequired':['Completed','Failed']},
'commandState':{'Queued':['Sent','Expired'],'Sent':['Accepted','Rejected','Unknown','Expired'],'Accepted':['Succeeded','Failed','Unknown','Expired'],'Unknown':['Succeeded','Failed','Expired']},
'paymentState':{'Created':['Authorized','Failed','Cancelled'],'Authorized':['PartiallyCaptured','Captured','Failed','Cancelled'],'PartiallyCaptured':['Captured','Refunded'],'Captured':['Refunded']},
'reservationState':{'Pending':['Active','Rejected','Expired'],'Active':['Consumed','Cancelled','Expired']},
'subscriptionState':{'Pending':['Active','Cancelled'],'Active':['Suspended','Cancelled','Expired'],'Suspended':['Active','Cancelled','Expired']},
'issueState':{'Open':['Acknowledged','Investigating','Resolved'],'Acknowledged':['Investigating','Resolved'],'Investigating':['Resolved'],'Resolved':['Closed','Open']},
'deploymentState':{'Scheduled':['Downloading','Failed'],'Downloading':['Downloaded','Failed'],'Downloaded':['Installing','Failed'],'Installing':['Succeeded','Failed'],'Succeeded':['RolledBack'],'Failed':['RolledBack']},
'invitationState':{'Pending':['Accepted','Declined','Expired','Revoked']},
'activationState':{'Requested':['Accepted','Rejected'],'Accepted':['Active','Failed'],'Active':['Completed','Failed']}}
transitions.update(json.loads((P/'model/lifecycle-policies.json').read_text()))
g=Graph();g.bind('cd',C);g.bind('sh',SH)
for r in rules:
 n=C[r['id']];b=BNode();g.add((n,RDF.type,SH.NodeShape));g.add((n,SH.targetClass,C[r['target']]));g.add((n,SH.sparql,b));g.add((b,SH.message,Literal(r['id']+': '+r['message'])));g.add((b,SH.select,Literal(r['query'])))
 standalone=r['query'].replace('WHERE { ','WHERE { $this rdf:type/rdfs:subClassOf* cd:'+r['target']+' . ',1).replace('$this','?this')
 (P/f'queries/{r["id"]}.rq').write_text(standalone+'\n')
(P/'validation/business.shacl.ttl').write_text(g.serialize(format='turtle'));(P/'model/rules.json').write_text(json.dumps(rules,indent=2));(P/'model/transitions.json').write_text(json.dumps(transitions,indent=2))
from rdflib import OWL,RDFS
trans=Graph();trans.bind('cd',C)
for prop in ['transitionProperty','fromState','toState']:trans.add((C[prop],RDF.type,OWL.ObjectProperty))
trans.add((C.TransitionRule,RDF.type,OWL.Class))
for p,states in transitions.items():
 for start,ends in states.items():
  for end in ends:
   n=C['transition_'+p+'_'+start+'_'+end];trans.add((n,RDF.type,C.TransitionRule));trans.add((n,C.transitionProperty,C[p]));trans.add((n,C.fromState,C[p+'_'+start]));trans.add((n,C.toState,C[p+'_'+end]))
(P/'ontology/transitions.ttl').write_text(trans.serialize(format='turtle'))
(P/'docs/validation-rules.md').write_text('# Cross-domain business validation\n\nThese are canonical domain policies. Vendor-specific restrictions belong in the separate External platform compatibility profile. SELECT results are violations; absence of rows is meaningful only after structural validation over a complete authorized snapshot.\n\n| Rule | Target | Invariant |\n|---|---|---|\n'+'\n'.join('| '+r['id']+' | '+r['target']+' | '+r['message']+' |' for r in rules)+'\n')
print(len(rules),'business rules',sum(len(v) for s in transitions.values() for v in s.values()),'allowed transitions')
